### ISSUE TITLE
Example of actions with dependencies using conda

### ISSUE THREAD

**Issue by jchiquet** [quarto-dev/quarto-actions#47]
Hi,

I had trouble using miniconda (setup-miniconda@v2 + environment.yml) in conjunction with the quarto publishing action to add Python modules and dependencies. On the other hand, all this worked with setup-python@v4 and the use of pip and a requirements.txt file.
See workflow here (use of conda commented) https://github.com/computorg/published-paper-tsne/actions/runs/3257812600/workflow

Did I misconfigure something? Maybe I didn't activate the right environment? Adding an entry with (mini)conda among the usage examples with dependencies would be very helpful.

Thanks

**Comment by lwasser** [comment]
hey @jchiquet 👋  i'm running into a similar issue. it looks like you ended up just pip installing jupyter? but i would love to use my conda envt in my action. all works locally but not in an action. did you aver make any progress or receive help on this?

[my workflow is here](https://github.com/data-science-skills/dsk/blob/initial-site/.github/workflows/build-site.yml) i run into Jupyter not found /nbformat not found errors when i build.

**Comment by jchiquet** [comment]
Hi!
I was using conda but in use, for simple Python projects, pip and venv proved to be easier to manage.

Nevertheless, here are two examples in the context of our journal using conda (with micromambda) and quarto with the Jupyter kernel.

- https://github.com/computorg/published-202301-chagneux-macrolitter/actions/runs/4213898162/workflow
- https://github.com/computorg/published-paper-tsne/actions/runs/4094221283/workflow

Hopefully this helps!

**Comment by lwasser** [comment]
hi @cderv you know i could NOT get this to work. 

It looks like @jchiquet did get it to work but for me [it always returned a "cant find jupyter" error ](https://github.com/data-science-skills/dsk/actions/runs/4219003819/jobs/7323966637#step:5:35). i got this error locally until i discovered `QUARTO_ENV` and set the environment there. but i didn't understand how these actions install into a conda envt. Below is what CI was returning

```
Starting python3 kernel...Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 17, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
Python 3 installation:
  Version: 3.10.9 (Conda)
  Path: /opt/conda/bin/python
  Jupyter: (None)

Jupyter is not available in this Python installation.
Install with conda install jupyter

There is a environment.yml file in this directory. Is this for a conda env that you need to restore?
```

[I ended up creating a docker container with mambaforge in it and installed quarto directly. ](https://github.com/data-science-skills/dsk/blob/main/.github/workflows/build-site.yml#L11)
That's been working well and i think is a bit faster especially when i need to add more packages to my envt. But these actions were really hard for me to work with using conda and i suspect others will have similar issues. i found another quarto build that did a similar thing using docker with python.

**Comment by jchiquet** [comment]
Hi @cderv , sorry it took me so long to answer.

Here is an example of micromamba setup which fails when using the quarto publish action, using the knitr kernel (fails with message `'Error in loadNamespace(x) : there is no package called ‘jsonlite’`

https://github.com/computorg/computo-quarto-extension/actions/runs/4192833325/workflow

This work with direct call to quarto, like that:
https://github.com/computorg/computo-quarto-extension/actions/runs/4193154092/workflow

(
A bit unrelated but when using Julia + the Jupyter Kernel and julia-1.8, I add to explicitly install a system jupyter (via apt) so that the quarto rendering works:
https://github.com/computorg/template-computo-julia/blob/main/.github/workflows/build.yml
)

**Comment by lwasser** [comment]
it seems like there is a default envt that these actions assume you are using? especially if you have to use apt to install jupyter @jchiquet ?

**Comment by cderv** [comment]
> But everything works fine on my side for now.

Because you switch from Miniconda, right ? I'll set a test repo with conda to see how it goes.

**Comment by jchiquet** [comment]
> Because you switch from Miniconda, right ?
For advanced examples with quarto + Python, yes...

> I'll set a test repo with conda to see how it goes.
I'll be happy to give my feedback from past 'miniconda' experiences, if it can help
