### ISSUE TITLE
publish multiple slideshows at once?

### ISSUE THREAD

**Issue by pvgenuchten** [quarto-dev/quarto-actions#91]
When i publish a single slideshow (revealjs), this action works nice, however if the path contains 2 slideshows (qmd files), i receive an error:

```
ERROR: The specified path (slides) is not a website or book project so cannot be published.
```

repo at https://github.com/pvgenuchten/slides

**Comment by pvgenuchten** [comment]
mmm, apparently is not related to the action, but to quarto, locally the same

```
$ quarto publish gh-pages ./slides --no-render --no-browser
ERROR: The specified path (./slides) is not a website or book project so cannot be published.

Stack trace:
    at createPublishOptions (file:///opt/quarto/bin/quarto.js:105064:19)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async publishAction (file:///opt/quarto/bin/quarto.js:104977:28)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:104972:9)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8111:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:111631:5)
    at async file:///opt/quarto/bin/quarto.js:111649:9
```
